name: build-web
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Flutter - setup SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Insert secrets
        run: echo -n "${{secrets.FIREBASE_OPTIONS}}" > ./lib/firebase_options.dart
      - name: Flutter - build application
        run: flutter build web --release
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4